kind: ConfigMap
apiVersion: v1
metadata:
  name: database-host
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  url: {{ .Values.database.name }}
