kind: ConfigMap
apiVersion: v1
metadata:
  name: xraylabdb-init
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
data:
  90-init-data.sh: |
    init_database() {
        local thisdir
        local init_data_file
        thisdir=$(dirname ${BASH_SOURCE[0]})

        init_data_file=$(readlink -f ${thisdir}/../mysql-data/schema.sql)
        log_info "Initializing the database schema from file ${init_data_file}..."
        mysql $mysql_flags ${MYSQL_DATABASE} < ${init_data_file}

        init_data_file=$(readlink -f ${thisdir}/../mysql-data/import.sql)
        log_info "Initializing the database data from file ${init_data_file}..."
        mysql $mysql_flags ${MYSQL_DATABASE} < ${init_data_file}
    }

    #if ! [ -v MYSQL_RUNNING_AS_SLAVE ] && $MYSQL_DATADIR_FIRST_INIT ; then
        init_database
        #fi

  import.sql: >-
    INSERT INTO `images_uploaded` (`time`,`name`) SELECT CURRENT_TIMESTAMP(), '';

    INSERT INTO `images_processed` (`time`,`name`,`model`,`label`) SELECT CURRENT_TIMESTAMP(), '', '','';

    INSERT INTO `images_anonymized` (`time`,`name`) SELECT CURRENT_TIMESTAMP(), '';

  schema.sql: >-
    DROP TABLE IF EXISTS `images_uploaded`;

    DROP TABLE IF EXISTS `images_processed`;

    DROP TABLE IF EXISTS `images_anonymized`;

    CREATE TABLE `images_uploaded` (`time` TIMESTAMP, `name` VARCHAR(255));

    CREATE TABLE `images_processed` (`time` TIMESTAMP, `name` VARCHAR(255), `model` VARCHAR(10), `label` VARCHAR(20));

    CREATE TABLE `images_anonymized` (`time` TIMESTAMP, `name` VARCHAR(255));
