---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: xraydb-external-secret
  namespace: {{ .Values.global.xraylab.namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  refreshInterval: 15s
  secretStoreRef:
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: db-secret
    template:
      type: Opaque
  dataFrom:
  - extract:
      key: {{ .Values.xraylabsecret.key }}
